### ISSUE TITLE
Cannot process weed

### ISSUE THREAD

**Issue by Domitresku** [esx-framework/esx_drugs#134]
Hello. Title says all. When I try to process weed, it doesn't give any error, it doesn't remove 3 cannabis, and it even doesn't add 1 marijuana. I tried to fix it, but failed. Does anybody know, how to fix it? Thanks for advices.

Peace ✌️

**Comment by Rikydc01** [comment]
Hi, i Merged the code which actually make 1 marijuana from 3 of cannabis but it works... Could you pls try to debug or let us know something more about your bug?

**Comment by Domitresku** [comment]
Hello. When I try to process drugs, it just doesnt work. No error, nothing.

Dňa št 10. 9. 2020, 20:15 Rikydc01 <notifications@github.com> napísal(a):

**Comment by Rikydc01** [comment]
You must have your marijuana and, got into the processing zone there should appear a message on the left-upper corner telling you to press E to process; is this correct?

**Comment by Domitresku** [comment]
Hello, sure, that is right


Dňa ut 15. 9. 2020, 22:56 Rikydc01 <notifications@github.com> napísal(a):

**Comment by Rikydc01** [comment]
So pressing E, nothing happens, right? could you pls check if you actually have some marijuana in your inventory and if your inventory script and esx_drugs are configured in the right way. Without any imgs and text it's really difficult to help you...

**Comment by Domitresku** [comment]
I will send images tomorrow, i have 23:05 in my country

Dňa ut 15. 9. 2020, 23:04 Rikydc01 <notifications@github.com> napísal(a):

**Comment by Rikydc01** [comment]
No problem, i hope i will help you! Here 23:05 too! :)

**Comment by Gregory-Hepicloud** [comment]
Hi do you find fix ? we have same problem no error in client or server thx :)

**Comment by itschip** [comment]
Should be fixed on last commit.
